{% set version = "0.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-deepnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/deepnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/deepnet/deepnet_{{ version }}.tar.gz
  sha256: 0f66d359269aecb03ca17d059004bb3dfc5dd1cd218baf544342ea030028ce3e

build:
  merge_build_host: true  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('deepnet')"           # [not win]
    - "\"%R%\" -e \"library('deepnet')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=deepnet
  summary: Implement some deep learning architectures and neural network algorithms, including BP,RBM,DBN,Deep autoencoder and so on.
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa


# Package: deepnet
# Type: Package
# Title: deep learning toolkit in R
# Version: 0.2
# Date: 2014-03-20
# Author: Xiao Rong
# Maintainer: Xiao Rong <runxiao@gmail.com>
# Description: Implement some deep learning architectures and neural network algorithms, including BP,RBM,DBN,Deep autoencoder and so on.
# License: GPL
# Packaged: 2014-03-20 08:06:35 UTC; xiaorong.xr
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-03-20 10:03:43
